### ISSUE TITLE
[Docker] Docker-Compose Network 的坑

### ISSUE THREAD

**Issue by jimliu7434** [jimliu7434/Diary#30]
最近遇到的坑

***Docker-Compose*** 的 `scale` 可以幫助一次起多個 container，此時可以用 service name 直接透過 Docker 內建的 **DNS Server** 做 Load Balance

但沒想到這個功能如果是使用 `links` 做 container 網路串連方式的話就會無法使用；使用 `networks` 做串聯才有作用

### ex:

- Nginx 設定如下

  ```
  server {
      listen  80 default_server;
      location / {
          proxy_pass http://app:8000;
      }
  }
  ```

- 如果使用 `links` 無法自動 load balance，**whoami** 看到的 container id 永遠都是同一個

  ```yml
  version: "2.3"

  services:
    app:
      image: jwilder/whoami:latest
      scale: 3
    nginx:
      image: nginx:1.15-alpine
      ports:
        - 8001:80
      depends_on:
        - app
      links:
        - app
      volumes:
        - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
  ```

- 使用 `networks` 才能正常 load balance，container id 會循 RR 輪循

  ```yml
  version: "2.3"

  services:
    app:
      image: jwilder/whoami:latest
      scale: 3
      networks:
        - balance
    nginx:
      image: nginx:1.15-alpine
      ports:
        - 8001:80
      depends_on:
        - app
      networks:
        - balance
      volumes:
        - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro

  networks:
    balance:
      driver: bridge
  ```
