### ISSUE TITLE
[Gitlab] CI Runner - 使用 Pipeline 進行 CI/CD

### ISSUE THREAD

**Issue by jimliu7434** [jimliu7434/Diary#38]
請先參考上篇 #37  啟用 Pipeline 並加入 Runner 

---

## 使用 `.gitlab-ci.yml` 控制 Pipeline 流程

Gitlab CI-Runner 為 Docker Base 的 CI/CD tools  
在沒有特別指定的情境下  
都會使用 docker 來執行 jobs   

Example：

```yaml
image: node:12

stages:
  - test
  - release
  - deploy

cache:
  untracked: true
  paths:
  - node_modules/

lint_mr:
  stage: test
  cache: {}
  before_script:
    - yarn
  script:
    - yarn lint
  only:
    - merge_requests
  except:
    changes:
      - .gitlab/**/*
      - .dockerignore
      - .gitignore
      - Dockerfile
      - README.md
      - .gitlab-ci.yml

unittest_mr:
  stage: test
  cache: {}
  before_script:
    - yarn
  script:
    - yarn test:ci
  only:
    - merge_requests
  except:
    changes:
      - .gitlab/**/*
      - .dockerignore
      - .gitignore
      - .eslintignore
      - .eslintrc.js
      - Dockerfile
      - README.md
      - .gitlab-ci.yml

unittest:
  stage: test
  cache: {}
  before_script:
    - yarn
  script:
    - yarn test:ci
  coverage: '/All files[^|]*\|[^|]*\s+([\d\.]+)/'
  artifacts:
    paths:
      - coverage/
  only:
    - master
  except:
    changes:
      - .gitlab/**/*
      - .dockerignore
      - .gitignore
      - .eslintignore
      - .eslintrc.js
      - Dockerfile
      - README.md
      - .gitlab-ci.yml

release-gitlab-semver:
  stage: release
  image:
    name: hutson/semantic-delivery-gitlab:9.1.0
    entrypoint: [""]
  script:
    - semantic-delivery-gitlab --token ${GITLAB_TOKEN}
  only:
    - master
  except:
    changes:
      - .gitlab/**/*
      - .dockerignore
      - .gitignore
      - .eslintignore
      - .eslintrc.js
      - Dockerfile
      - README.md
      - .gitlab-ci.yml

release:
  stage: release
  cache: {}
  tags:
    - deploy
  image: docker
  variables:
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: ""
    #IMAGE_NAME: "tgbot/server"
  services:
    - docker:dind
  script:
    - echo "image - $IMAGE_NAME:$CI_COMMIT_TAG"
    - docker build -t $IMAGE_NAME:$CI_COMMIT_TAG .
    - docker tag $IMAGE_NAME:$CI_COMMIT_TAG "$IMAGE_NAME:latest"
  after_script:
    - echo removing dangling images...
    - docker system prune -f
    - docker images | grep "$IMAGE_NAME:latest"
  only:
    - tags

deploy:
  stage: deploy
  cache: {}
  tags:
    - deploy
  image: docker
  variables:
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: ""
    #IMAGE_NAME: "tgbot/server"
  services:
    - docker:dind
  script:
    - echo "deploy - $IMAGE_NAME:$CI_COMMIT_TAG"
    - docker-compose -f docker-compose.yml up -d
  after_script:
    - docker ps | grep tgbot
  environment:
    name: production
  when: manual
  only:
    - tags
```

  * `image` 定義 default docker image
  * `stages` 定義 Pipeline 的各個階段
  * `cache` 定義可共用的檔案，節省 install or download 時間

## 使用 Pipeline 進行 Test

此處包含 Lint & Test 等 Code Quality  Checks

```yaml
lint_mr:
  stage: test
  cache: {}
  before_script:
    - yarn
  script:
    - yarn lint
  only:
    - merge_requests
  except:
    changes:
      - .gitlab/**/*
      - .dockerignore
      - .gitignore
      - Dockerfile
      - README.md
      - .gitlab-ci.yml

unittest_mr:
  stage: test
  cache: {}
  before_script:
    - yarn
  script:
    - yarn test:ci
  only:
    - merge_requests
  except:
    changes:
      - .gitlab/**/*
      - .dockerignore
      - .gitignore
      - .eslintignore
      - .eslintrc.js
      - Dockerfile
      - README.md
      - .gitlab-ci.yml

unittest:
  stage: test
  cache: {}
  before_script:
    - yarn
  script:
    - yarn test:ci
  coverage: '/All files[^|]*\|[^|]*\s+([\d\.]+)/'
  artifacts:
    paths:
      - coverage/
  only:
    - master
  except:
    changes:
      - .gitlab/**/*
      - .dockerignore
      - .gitignore
      - .eslintignore
      - .eslintrc.js
      - Dockerfile
      - README.md
      - .gitlab-ci.yml
```

### job:  `lint_mr`

  1. 目的：執行 lint when merge_requests
  2. 未指定 image，使用 `node:12`
  3. 執行時機： merge_requests 有變化時，但排除部分不會影響打包的參數檔或設定檔
     (通常我們會鎖定 *master* branch 當作包版主幹，此時需透過 MR 才能讓 commit 進入 *master* branch )
  4. 預先執行 `yarn` 安裝 dependency
  5. 執行 `yarn lint` 呼叫寫好的 linting scripts (ex: eslint)

### job: `unittest_mr`

  1. 目的：執行 unit test when merge_requests
  1. 未指定 image，使用 `node:12`
  2. 執行時機： merge_requests 有變化時，但排除部分不會影響打包的參數檔或設定檔
  3. 預先執行 `yarn` 安裝 dependency
  4. 執行 `yarn test:ci` 呼叫寫好的 testing scripts (ex: jest)

### job: `unittest`

  1. 目的：執行 unit test when master branch changed
  1. 未指定 image，使用 `node:12`
  2. 執行時機： *master* branch 有變化時，但排除部分不會影響打包的參數檔或設定檔
  3. 預先執行 `yarn` 安裝 dependency
  4. 執行 `yarn test:ci` 呼叫寫好的 testing scripts (ex: jest)
  5. `coverage` 參數會將測試 log 過濾出關於覆蓋率的內容，並顯示在 Pipeline 上
  6. `artifacts` 參數指定 Pipeline 完成後的可下載項目內容，此處為覆蓋率 HTML Report
  
  ![image](https://user-images.githubusercontent.com/16040059/89994891-528a1e80-dcbb-11ea-9d6e-3c9ac1d7b99c.png)

p.s. Pipeline Status & Coverage 可以使用 **badges** 顯示在 readme 上  
詳細內容請參考 ***Settings > CI/CD >General pipelines***

  ![image](https://user-images.githubusercontent.com/16040059/89996071-ea3c3c80-dcbc-11ea-8f21-68c07c960b90.png)

  ![image](https://user-images.githubusercontent.com/16040059/89995107-a6950300-dcbb-11ea-8c09-736c43ddaefe.png)

---

## 使用 Pipeline 進行 Release

```yaml
release-gitlab-semver:
  stage: release
  image:
    name: hutson/semantic-delivery-gitlab:9.1.0
    entrypoint: [""]
  script:
    - semantic-delivery-gitlab --token ${GITLAB_TOKEN}
  only:
    - master
  except:
    changes:
      - .gitlab/**/*
      - .dockerignore
      - .gitignore
      - .eslintignore
      - .eslintrc.js
      - Dockerfile
      - README.md
      - .gitlab-ci.yml

release:
  stage: release
  cache: {}
  tags:
    - deploy
  image: docker
  variables:
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: ""
    #IMAGE_NAME: "tgbot/server"
  services:
    - docker:dind
  script:
    - echo "image - $IMAGE_NAME:$CI_COMMIT_TAG"
    - docker build -t $IMAGE_NAME:$CI_COMMIT_TAG .
    - docker tag $IMAGE_NAME:$CI_COMMIT_TAG "$IMAGE_NAME:latest"
  after_script:
    - echo removing dangling images...
    - docker system prune -f
    - docker images | grep "$IMAGE_NAME:latest"
  only:
    - tags
```

### job: `release-gitlab-semver`

  1. 目的：呼叫工具執行 Release：根據 Git Commit log 內容，決定新版本號、寫入 Release Note、押注 Git `tag`
  1. 指定 image 使用 `hutson/semantic-delivery-gitlab:9.1.0`
  2. 執行時機： *master* branch 有變化時，但排除部分不會影響打包的參數檔或設定檔
  3. 執行 `semantic-delivery-gitlab --token ${GITLAB_TOKEN}`  此處 GITLAB_TOKEN 為 ***Variables*** (請前往 ***Settings > CI/CD > Variables*** 進行設定)
  4. 對 Project 進行 Release 動作

### job: `release`

  1. 目的：建置 docker image
  1. image: `docker` 並設定 variables & service 如上， `dind` 意即 "docker in docker"，則等同在 docker base，呼叫 runner 原生 CLI
  2. 執行時機：Git `tag` 有變化時
  3. 指定 `tag = deploy` 表示指定使用某台 label = deploy 的 runner 來執行此 job
  4. 執行： docker build 建置 project，其中 `$CI_COMMIT_TAG` 為觸發此次執行的 Git `tag` 文字 = 版本號
  5. 後執行：因為 dockerfile 內使用 multi-stage build ，所以呼叫 `docker system prune` 清除無用的 images

---

## 使用 Pipeline 進行 Deploy

```yaml
deploy:
  stage: deploy
  cache: {}
  tags:
    - deploy
  image: docker
  variables:
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: ""
    #IMAGE_NAME: "tgbot/server"
  services:
    - docker:dind
  script:
    - echo "deploy - $IMAGE_NAME:$CI_COMMIT_TAG"
    - docker-compose -f docker-compose.yml up -d
  after_script:
    - docker ps | grep tgbot
  environment:
    name: production
  when: manual
  only:
    - tags
```

### job: `deploy`

  1. 目的：使用指定版本號的 docker image 進行部署
  1. image: `docker` 並設定 variables & service 如上，`dind` 意即 "docker in docker"，則等同在 docker base，呼叫 runner 原生 CLI
  2. 執行時機：Git `tag` 有變化時
  3. `when = manual` 代表當 `tag` 有變化時，此 job 會顯示在 pipeline，但需要手動進入 Pipeline 頁面按 `[Play]` 按鈕才會執行，此處設定代表 RD 可以自行決定什麼時間將早已打包好的 image 進行部署上指定機台

  ![image](https://user-images.githubusercontent.com/16040059/89994675-09d26580-dcbb-11ea-9211-6b3371a7f40d.png)

  5. 指定 `tag = deploy` 表示指定使用某台 label = deploy 的 runner 來執行此 job
  6. 執行： `docker-compose` 部署至主機上
  7. 後執行：`docker ps | grep tgobt` 查看專案是否啟動成功
  8. `environment` 紀錄各個環境分別的 deploy records
